export interface IDemoRestaurant {
  _id: string;
  name: string;
  slug: string;
  description: string;
  cuisine: string[];
  country: string;
  flag: string;
  address: string;
  phone: string;
  email: string;
  rating: number;
  totalReviews: number;
  minimumOrder: number;
  deliveryFee: number;
  estimatedDeliveryTime: number;
  isApproved: boolean;
  isActive: boolean;
  coverImage: string;
  logo: string;
}

export const WORLD_RESTAURANTS: IDemoRestaurant[] = [
  {
    _id: 'rest_italy_01',
    name: 'Trattoria Bella Italia',
    slug: 'trattoria-bella-italia',
    description: 'Authentic Italian woodfired pizzas, fresh handmade pastas, and classic gelato straight from Rome.',
    cuisine: ['Italian', 'Pizza', 'Pasta'],
    country: 'Italy',
    flag: '🇮🇹',
    address: 'Via Roma 45, Rome, Italy',
    phone: '+39 06 1234 5678',
    email: 'info@bellaitalia.it',
    rating: 4.9,
    totalReviews: 320,
    minimumOrder: 15,
    deliveryFee: 0,
    estimatedDeliveryTime: 25,
    isApproved: true,
    isActive: true,
    coverImage: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=200&q=80',
  },
  {
    _id: 'rest_france_02',
    name: 'Le Bistro Parisien',
    slug: 'le-bistro-parisien',
    description: 'Fine French dining featuring Duck Confit, Coq au Vin, fresh butter croissants, and exquisite pastries.',
    cuisine: ['French', 'Bistro', 'Pastries'],
    country: 'France',
    flag: '🇫🇷',
    address: '12 Rue de Rivoli, Paris, France',
    phone: '+33 1 42 68 55 00',
    email: 'contact@lebistroparisien.fr',
    rating: 4.9,
    totalReviews: 280,
    minimumOrder: 20,
    deliveryFee: 2.99,
    estimatedDeliveryTime: 30,
    isApproved: true,
    isActive: true,
    coverImage: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?auto=format&fit=crop&w=200&q=80',
  },
  {
    _id: 'rest_germany_03',
    name: 'Bavarian Brauhaus & Schnitzel',
    slug: 'bavarian-brauhaus',
    description: 'Hearty German Schnitzels, Currywurst, Sauerbraten, freshly baked Pretzels, and Apple Strudel.',
    cuisine: ['German', 'Schnitzel', 'Bavarian'],
    country: 'Germany',
    flag: '🇩🇪',
    address: 'Marienplatz 8, Munich, Germany',
    phone: '+49 89 2345 6789',
    email: 'servus@brauhaus.de',
    rating: 4.8,
    totalReviews: 245,
    minimumOrder: 15,
    deliveryFee: 1.99,
    estimatedDeliveryTime: 25,
    isApproved: true,
    isActive: true,
    coverImage: 'https://images.unsplash.com/photo-1599921841143-819065a55cc6?auto=format&fit=crop&w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=200&q=80',
  },
  {
    _id: 'rest_syria_04',
    name: 'Al-Sham Damascene Kitchen',
    slug: 'al-sham-kitchen',
    description: 'Authentic Syrian Cuisine: Shawarma Arabi, Kebbeh, Shish Barak, Fatteh, Yabraq, and Knefeh.',
    cuisine: ['Syrian', 'Middle Eastern', 'Kebabs'],
    country: 'Syria',
    flag: '🇸🇾',
    address: 'Old City Straight St, Damascus, Syria',
    phone: '+963 11 234 5678',
    email: 'info@alsham.sy',
    rating: 4.9,
    totalReviews: 410,
    minimumOrder: 10,
    deliveryFee: 0,
    estimatedDeliveryTime: 20,
    isApproved: true,
    isActive: true,
    coverImage: 'https://images.unsplash.com/photo-1529003600303-bd51f39627fb?auto=format&fit=crop&w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=200&q=80',
  },
  {
    _id: 'rest_switzerland_05',
    name: 'Alpine Swiss Fondue Chalet',
    slug: 'alpine-swiss-fondue',
    description: 'Traditional Swiss Cheese Fondue, Zürcher Geschnetzeltes, Rösti pancakes, and premium Swiss chocolates.',
    cuisine: ['Swiss', 'Fondue', 'Alpine'],
    country: 'Switzerland',
    flag: '🇨🇭',
    address: 'Bahnhofstrasse 10, Zurich, Switzerland',
    phone: '+41 44 211 3344',
    email: 'order@alpinefondue.ch',
    rating: 4.9,
    totalReviews: 290,
    minimumOrder: 25,
    deliveryFee: 3.5,
    estimatedDeliveryTime: 30,
    isApproved: true,
    isActive: true,
    coverImage: 'https://images.unsplash.com/photo-1541014741259-de529411b96a?auto=format&fit=crop&w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=200&q=80',
  },
  {
    _id: 'rest_egypt_06',
    name: 'Cairo Koshary & Pharaohs Grill',
    slug: 'cairo-koshary-grill',
    description: 'Egyptian Heritage: Koshary Supreme, Sizzling Hawawshi, Molokhia with Chicken, Roz Bel Laban, and Umm Ali.',
    cuisine: ['Egyptian', 'Middle Eastern', 'Koshary'],
    country: 'Egypt',
    flag: '🇪🇬',
    address: 'Tahrir Square 15, Cairo, Egypt',
    phone: '+20 2 2345 6789',
    email: 'contact@cairogrill.eg',
    rating: 4.8,
    totalReviews: 350,
    minimumOrder: 10,
    deliveryFee: 1.0,
    estimatedDeliveryTime: 20,
    isApproved: true,
    isActive: true,
    coverImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=200&q=80',
  },
  {
    _id: 'rest_japan_07',
    name: 'Sakura Tokyo Ramen & Sushi',
    slug: 'sakura-tokyo',
    description: 'Authentic Japanese Tonkotsu Ramen, Fresh Sashimi, Dragon Sushi Rolls, and Matcha Desserts.',
    cuisine: ['Japanese', 'Sushi', 'Ramen'],
    country: 'Japan',
    flag: '🇯🇵',
    address: 'Shibuya Crossing 4-1, Tokyo, Japan',
    phone: '+81 3 3461 8899',
    email: 'info@sakuratokyo.jp',
    rating: 4.9,
    totalReviews: 450,
    minimumOrder: 20,
    deliveryFee: 2.5,
    estimatedDeliveryTime: 25,
    isApproved: true,
    isActive: true,
    coverImage: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=200&q=80',
  },
  {
    _id: 'rest_usa_08',
    name: 'American Prime Burger & BBQ',
    slug: 'american-prime-bbq',
    description: 'Handcrafted Angus Smash Burgers, Slow Smoked BBQ Ribs, Buffalo Wings, and New York Cheesecake.',
    cuisine: ['American', 'Burgers', 'BBQ'],
    country: 'USA',
    flag: '🇺🇸',
    address: '5th Avenue 742, New York, USA',
    phone: '+1 (212) 555-0199',
    email: 'bbq@americanprime.com',
    rating: 4.8,
    totalReviews: 380,
    minimumOrder: 15,
    deliveryFee: 1.5,
    estimatedDeliveryTime: 20,
    isApproved: true,
    isActive: true,
    coverImage: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=200&q=80',
  },
  {
    _id: 'rest_mexico_09',
    name: 'El Taco Loco & Cantina',
    slug: 'el-taco-loco-cantina',
    description: 'Authentic Street Tacos Al Pastor, Cheesy Birria Tacos, Burritos, Sizzling Fajitas, and Crispy Churros.',
    cuisine: ['Mexican', 'Tacos', 'Tex-Mex'],
    country: 'Mexico',
    flag: '🇲🇽',
    address: 'Av. Reforma 222, Mexico City, Mexico',
    phone: '+52 55 5234 5678',
    email: 'hola@eltacoloco.mx',
    rating: 4.8,
    totalReviews: 295,
    minimumOrder: 12,
    deliveryFee: 1.99,
    estimatedDeliveryTime: 22,
    isApproved: true,
    isActive: true,
    coverImage: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=200&q=80',
  },
  {
    _id: 'rest_india_10',
    name: 'Taj Mahal Indian Palace',
    slug: 'taj-mahal-palace',
    description: 'Aromatic Butter Chicken, Lamb Biryani, Chicken Tikka Masala, Fresh Garlic Naan, and Gulab Jamun.',
    cuisine: ['Indian', 'Curry', 'Biryani'],
    country: 'India',
    flag: '🇮🇳',
    address: 'Connaught Place 12, New Delhi, India',
    phone: '+91 11 2334 5566',
    email: 'orders@tajmahalpalace.in',
    rating: 4.9,
    totalReviews: 310,
    minimumOrder: 15,
    deliveryFee: 0,
    estimatedDeliveryTime: 30,
    isApproved: true,
    isActive: true,
    coverImage: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=200&q=80',
  },
  {
    _id: 'rest_spain_11',
    name: 'Casa Real Tapas & Paella',
    slug: 'casa-real-spain',
    description: 'Authentic Spanish Seafood Paella, Tapas, Gazpacho soup, Jamón Ibérico, and churros.',
    cuisine: ['Spanish', 'Paella', 'Tapas'],
    country: 'Spain',
    flag: '🇪🇸',
    address: 'La Rambla 88, Barcelona, Spain',
    phone: '+34 93 123 4567',
    email: 'tapas@casareal.es',
    rating: 4.9,
    totalReviews: 340,
    minimumOrder: 18,
    deliveryFee: 2.0,
    estimatedDeliveryTime: 25,
    isApproved: true,
    isActive: true,
    coverImage: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?auto=format&fit=crop&w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=200&q=80',
  },
  {
    _id: 'rest_saudi_12',
    name: 'Al-Qasr Royal Saudi Mandi & Kabsa',
    slug: 'al-qasr-saudi',
    description: 'Authentic Saudi Royal Lamb Kabsa, Chicken Mandi, Saleeg, Madghout, and Maamoul dates.',
    cuisine: ['Saudi', 'Kabsa', 'Mandi'],
    country: 'Saudi Arabia',
    flag: '🇸🇦',
    address: 'King Fahd Rd, Riyadh, Saudi Arabia',
    phone: '+966 11 456 7890',
    email: 'info@alqasr.sa',
    rating: 4.9,
    totalReviews: 480,
    minimumOrder: 20,
    deliveryFee: 0,
    estimatedDeliveryTime: 25,
    isApproved: true,
    isActive: true,
    coverImage: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=200&q=80',
  },
  {
    _id: 'rest_turkey_13',
    name: 'Sultanahmet Turkish Doner & Kebab',
    slug: 'sultanahmet-turkish',
    description: 'Authentic Turkish Iskender Kebab, Adana Kebab, Lahmacun, Pide, and Turkish Delight.',
    cuisine: ['Turkish', 'Kebabs', 'Pide'],
    country: 'Turkey',
    flag: '🇹🇷',
    address: 'Istiklal Ave 104, Istanbul, Turkey',
    phone: '+90 212 345 6789',
    email: 'kebab@sultanahmet.tr',
    rating: 4.9,
    totalReviews: 390,
    minimumOrder: 12,
    deliveryFee: 1.5,
    estimatedDeliveryTime: 20,
    isApproved: true,
    isActive: true,
    coverImage: 'https://images.unsplash.com/photo-1529003600303-bd51f39627fb?auto=format&fit=crop&w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=200&q=80',
  },
  {
    _id: 'rest_lebanon_14',
    name: 'Beirut Cedar Grill & Mezza',
    slug: 'beirut-cedar-lebanon',
    description: 'Lebanese Mezza: Tabbouleh, Fattoush, Shish Taouk, Manakish Zaatar, and Creamy Hummus.',
    cuisine: ['Lebanese', 'Mezza', 'Shawarma'],
    country: 'Lebanon',
    flag: '🇱🇧',
    address: 'Hamra Main St, Beirut, Lebanon',
    phone: '+961 1 350 400',
    email: 'info@beirutcedar.lb',
    rating: 4.9,
    totalReviews: 420,
    minimumOrder: 15,
    deliveryFee: 1.0,
    estimatedDeliveryTime: 20,
    isApproved: true,
    isActive: true,
    coverImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=200&q=80',
  },
  {
    _id: 'rest_morocco_15',
    name: 'Marrakech Tajine & Couscous House',
    slug: 'marrakech-tajine-morocco',
    description: 'Traditional Moroccan Lamb Tajine with Prunes, Royal Couscous, Chicken Pastilla, and Mint Tea treats.',
    cuisine: ['Moroccan', 'Tajine', 'Couscous'],
    country: 'Morocco',
    flag: '🇲🇦',
    address: 'Jemaa el-Fnaa, Marrakech, Morocco',
    phone: '+212 524 380 900',
    email: 'marrakech@tajinehouse.ma',
    rating: 4.8,
    totalReviews: 310,
    minimumOrder: 15,
    deliveryFee: 2.0,
    estimatedDeliveryTime: 25,
    isApproved: true,
    isActive: true,
    coverImage: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=200&q=80',
  },
];
